trigger: none
pr: none

parameters:
  - name: tag
    displayName: 'Ingresar tag para ejecución (ej: @login)'
    type: string
    default: '@login'

pool:
  vmImage: 'windows-latest'

variables:
  SERENITY_ENV: 'dev'

stages:
  - stage: RunTests
    displayName: Run Serenity BDD Tests
    jobs:
      - job: RunTestsJob
        steps:
          - checkout: self

          - task: JavaToolInstaller@0
            inputs:
              versionSpec: '17'
              jdkArchitectureOption: 'x64'
              jdkSourceOption: 'PreInstalled'

          - task: Cache@2
            inputs:
              key: 'maven | "$(Agent.OS)" | **/pom.xml'
              restoreKeys: |
                maven | "$(Agent.OS)"
              path: '$(UserProfile)\.m2\repository'

          - script: |
              mvn clean verify -Denvironment=dev -Dcucumber.filter.tags="${{ parameters.tag }}"
            displayName: Ejecutar pruebas con Maven

          - task: PublishBuildArtifacts@1
            displayName: 'Publicar Reporte Serenity en Artifacts AzureDevops'
            inputs:
              pathToPublish: 'target\site\serenity'
              artifactName: 'serenity-report'
              publishLocation: 'Container'
